-- Script não rodou, verificar com a UFRN

-- #447668 - Criação tabela e inserção de dados

-- script necessário apenas no caso de implantação do novo portal público do sigrh, utilizado para preencher informações de caso de uso utilizado na busca geral do sistema.
/*
CREATE FUNCTION adicionaCasosDeUsoSigrhPublicoLink()
RETURNS varchar AS $$
DECLARE linkSigrh varchar;
DECLARE linkSigrhPublico varchar;
DECLARE siglaInstituicao varchar;
        begin
        	SELECT valor INTO siglaInstituicao  from comum.dados_institucionais WHERE nome = 'siglaInstituicao';
	        SELECT (valor || '/sigrh/') INTO linkSigrh from comum.dados_institucionais where nome = 'linkSigrh';
			SELECT (url || '/') INTO linkSigrhPublico  from comum.sistema s  WHERE descricao = 'SIGRH PUBLICO';
	   
	       	INSERT INTO comum.caso_uso_publico VALUES 
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Concursos abertos',
				'Permite realizar inscrição dos concursos abertos.',
				linkSigrhPublico || 'concursos/abertos',
				7,
				100900),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Concursos em andamento',
				'Permite acompanhar os concursos em andamento visualizando editais, portarias, resoluções, entre outros.',
				linkSigrhPublico || 'concursos/em-andamento',
				7,
				100900),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Área do candidato',
				'Permite acompanhar o andamento do concurso além de demais consultas como GRU, reconsideração, documentos do concurso, entre outros.',
				linkSigrh || 'public/concursos/area_candidato/form_login.jsf',
				7,
				100900),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Ausências',
				'Permite realizar uma consulta das ausências do servidor registradas no sistema.',
				linkSigrh || 'public/consultarServicoPublico/ausencias',
				7,
				102000),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Averbações',
				'Permite realizar uma consulta das averbações do servidor registradas no sistema.',
				linkSigrh || 'public/consultarServicoPublico/averbacoes',
				7,
				102000),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Benefícios',
				'Permite realizar uma consulta dos benefícios do servidor registrados no sistema.',
				linkSigrh || 'public/consultarServicoPublico/beneficios',
				7,
				102000),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Dependentes',
				'Permite realizar uma consulta dos dependentes vinculados ao servidor que estão registrados no sistema.',
				linkSigrh || 'public/consultarServicoPublico/dependentes',
				7,
				102000),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Designações de função',
				'Permite a consulta de designações de funções dos servidores de acordo com ano ou unidade.',
				linkSigrh || 'public/consultarServicoPublico/designacoes',
				7,
				102000),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Extrato funcional',
				'Permite a consulta dos dados funcionais do servidor que estão registrados no sistema.',
				linkSigrh || 'public/consultarServicoPublico/extrato-funcional',
				7,
				102000),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Férias',
				'Permite realizar uma consulta das férias do servidor registradas no sistema.',
				linkSigrh || 'public/consultarServicoPublico/ferias',
				7,
				102000),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Ficha financeira',
				'Permite realizar uma consulta da ficha financeira do servidor registrada no sistema.',
				linkSigrh || 'public/consultarServicoPublico/ficha-financeira',
				7,
				102000),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Licenças adquiridas',
				'Permite realizar uma consulta das licenças adquiridas por tempo de serviço do servidor registradas no sistema.',
				linkSigrh || 'public/consultarServicoPublico/aquisitivos',
				7,
				102000),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Previsão de aposentadoria',
				'Permite realizar uma consulta da previsão de aposentadoria do servidor registrada no sistema.',
				linkSigrh || 'public/consultarServicoPublico/aposentadoria',
				7,
				102000),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Progressões',
				'Permite realizar uma consulta dos benefícios do servidor registrados no sistema.',
				linkSigrh || 'public/consultarServicoPublico/progressoes',
				7,
				102000),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Servidores',
				'Permite consultar os servidores da instituição de acordo com nome ou unidade.',
				linkSigrhPublico || 'servidores',
				7,
				102000),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Documentos Oficiais',
				'Permite visualizar os documentos oficiais da instituição.',
				linkSigrhPublico || 'resolucoes',
				7,
				100800),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Resoluções',
				'Permite realizar uma busca nas resoluções publicadas pelo colegiados.',
				linkSigrhPublico || 'resolucoes',
				7,
				100800),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Pautas e atas',
				'Permite realizar uma busca nas pautas e atas publicadas pelo colegiados.',
				linkSigrhPublico || 'resolucoes',
				7,
				100800),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Composição',
				'Permite consultar a composição dos membros dos conselhos superiores.',
				linkSigrhPublico || 'resolucoes',
				7,
				100800),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Documentos',
				'Permite encontrar os documentos públicos cadastrados no sigrh.',
				linkSigrhPublico || 'documentos',
				7,
				100000),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Plano de carreira',
				'Permite buscar os documentos relacionados ao plano de carreira P.C.C.T.A.E.',
				linkSigrhPublico || 'documentos/plano-carreira',
				7,
				100000),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Autenticação de documentos',
				'Confirmação da validade dos documentos emitidos pelo SIGRH.',
				linkSigrhPublico || 'autenticacao-documentos',
				7,
				100000),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Plano de desenvolvimento',
				'Plano de desenvolvimento dos integrantes da carreira dos cargos técnicos-administrativos.',
				linkSigrhPublico || 'documentos/PLANO_DESENVOL_INST_CARREIRA_TA.doc',
				7,
				100000),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Programa de qualificação',
				'Regulamentação do Programa de Qualificação e Educação Profissional para os servidores.',
				linkSigrhPublico || 'documentos/Resolucao_16_consad_PQEP.doc',
				7,
				100000),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Relatórios mensais',
				'Permite consultar os relatórios estatísticos mensais da instituição.',
				linkSigrhPublico || 'relatorios',
				7,
				100000),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Relatórios anuais',
				'Permite consultar os relatórios estatísticos anuais da instituição.',
				linkSigrhPublico || 'relatorios',
				7,
				100000),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Acompanhar/Solicitar',
				'Faça uma solicitação eletrônica para a Administração de Pessoal. Seja atendido com rapidez e comodidade.',
				linkSigrh || 'public/consultarServicoPublico/solicitacao-eletronica',
				7,
				101700),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Agendar evento',
				'Agende um encontro com um dos nossos pró-reitores. Seja atendido com rapidez e comodidade.',
				linkSigrhPublico || 'servicos/buscar-evento',
				7,
				102500),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Requerimentos',
				'Visualize vários formulários de requerimentos.',
				linkSigrh || 'public/consultarServicoPublico/formularios-requerimentos',
				7,
				102000),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Abono',
				'Imprima o formulário de abono de permanência.',
				linkSigrh || 'public/consultarServicoPublico/formularios-abono',
				7,
				102000),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Aposentadoria',
				'Imprima o formulário de solicitação de aposentadoria.',
				linkSigrh || 'public/consultarServicoPublico/formularios-aposentadoria',
				7,
				102000),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Termo de Afastamento',
				'Imprima o termo de afastamento.',
				linkSigrh || 'public/consultarServicoPublico/formularios-afastamento',
				7,
				102000),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Auxílio Transporte',
				'Faça o recadastramento das linhas de transportes utilizadas em seu deslocamento até a '||siglaInstituicao||'.',
				linkSigrh || 'public/consultarServicoPublico/recadastramentos-auxilio-transporte',
				7,
				100100),
				(nextval('comum.caso_uso_publico_seq'),
				NULL,
				'Cadastro de Dependentes',
				'Realize o cadastro eletrônico de seus dependentes.',
				linkSigrh || 'public/consultarServicoPublico/recadastramentos-dependentes',
				7,
				100100);
					       	
	       return linkSigrh;
        END;
$$ LANGUAGE plpgsql;

SELECT adicionaCasosDeUsoSigrhPublicoLink();
DROP FUNCTION if exists adicionaCasosDeUsoSigrhPublicoLink();

 */